spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 260386166611-2a5mf7i3k06cviagevds2cj9rs3hebl2.apps.googleusercontent.com
            client-secret: KwPRGe6zihiCLy_jogklcTgA
            scope: profile, email
          kakao:
            client-id: ae5982740cb07c3f43a09439c98fb997
            client-secret: nTAItiV7Mfu6mjcQj7iaT7eveO4WxvHR
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
          naver:
            client-id: W7lbNdKTFQY0_reDue3D
            client-secret: Jd9XzKsdhw
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope: profile
            client-name: Naver
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
