spring:
  application:
    name: tms
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: create
    open-in-view: true
  datasource:
    platform: h2
    driver-class-name: org.h2.Driver
    url: "jdbc:h2:mem:tms;MODE=MYSQL;DB_CLOSE_DELAY=-1"
    username: sa
    password:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: H2_DB
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

logging:
  level:
    root: info
    com:
      mhkim:
        tms: debug
