spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: client
            client-secret: client-secret
            scope: profile, email
          kakao:
            client-id: client
            client-secret: client-secret
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile
            client-name: Kakao
            authorization-grant-type: authorization_code
            client-authentication-method: POST
          naver:
            client-id: client
            client-secret: client-secret
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            scope: profile
            client-name: Naver
            authorization-grant-type: authorization_code
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
