server:
  port: 8081
  servlet:
    context-path: /tms

spring:
  profiles:
    include: oauth2, opendata

  messages:
    basename: i18n/messages
    encoding: UTF-8
    cache-duration: PT1H

  session:
    store-type: jdbc
  
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true
    
  datasource:
    url: "jdbc:mariadb://{ip}:{port}/{database}?characterEncoding=utf8&serverTimezone=Asia/Seoul"
    username:
    password:
    driver-class-name: org.mariadb.jdbc.Driver
      
  batch:
    job:
      enabled: false

logging:
  level:
    root: INFO
    com:
      mhkim: DEBUG
